name: youtuber-bidding-app
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/app
      - node_modules:/app/node_modules
      - svelte_kit:/app/.svelte-kit
    env_file:
      - ../env/.env.dev
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_PUBLIC_API_URL=http://api:8000/api
    ports:
      - '5173:5173'
    restart: unless-stopped
    networks:
      - youtuber-bidding

networks:
  youtuber-bidding:
    external: true

volumes:
  node_modules:
  svelte_kit:
